### ISSUE TITLE
[.github]: config.yaml includes an invalid reference to the API-design-guidelines.md

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/QualityOnDemand_PI1#14]
**Describe the bug**
The reference to the API-Design-guidelines is invalid: https://github.com/camaraproject/QualityOnDemand_PI1/blob/main/.github/ISSUE_TEMPLATE/config.yml

```yaml
- name: 📖 CAMARA API Design Guidelines
    url: https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-design-guidelines.md
    about: Please refer to the design guidelines.
```

**Expected behavior**
```yaml
- name: 📖 CAMARA API Design Guidelines
    url: https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md
    about: Please refer to the design guidelines.
```
