### ISSUE TITLE
[BUG]: RedisConfig is pointing to an invalid configuration of Redis-Host & -port

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/QualityOnDemand_PI1#5]
## Bug description
The application cannot start with the "default"-profile caused by a misleading RedisConfig in the application.yaml

### application.yaml
Here redis is configured with _spring.redis.host_ and _spring.redis.port_. (Starting with Spring-Boot v3.0.0)

```yaml
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: localhost
      port: 6379
```
### Current RedisConfig

```java

public class RedisConfig {

<...>

  @Value("${spring.redis.port}") // Config is pointing to spring.redis.port (was working for versions < Spring-Boot v3.0.0)
  private int redisPort;

  @Value("${spring.redis.host}") // Config is pointing to spring.redis.host(was working for versions < Spring-Boot v3.0.0)
  private String redisHost;

<...>
```
